document.write("");
document.write("    <div class=\"pilihlist\">");
document.write("        <button onclick=\"btn('serial')\">Serial</button>");
document.write("        <button onclick=\"btn('Web')\">Web</button>");
document.write("    </div>");
document.write("    <div class=\"containerlist\">");
document.write("        <div class=\"serial\" id=\"serialmanga\">");
document.write("            <h4>Manga Serial</h4>");
document.write("            <div class=\"cardo\">");
document.write("                <div class=\"list ichika\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Tsuka no Ma no Ichika</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list hatsukoi\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Hatsukoi Maze</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list cuprum\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Cuprum's Bride</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list trinity\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Okyu no Trinity</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list isekai\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Ikidaore mo Dekinai Konna Isekai Ja</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list rokudo\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Rokudo Tosoki</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list kuroha\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Kuroha to Nijisuke</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list accelerator\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Toaru Kagaku no Accelerator</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list koisuru\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Kimi ni Koisuru Satsujinki</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list dorei\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Kimi Janakya Damena Dorei Shoujo</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list parasite\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Parasite in Love</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list hyouka\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\">Hyouka</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("            </div>");
document.write("        </div>");
document.write("        <div class=\"web\" id=\"webmanga\">");
document.write("            <h4>Manga Web</h4>");
document.write("            <div class=\"cardo\">");
document.write("                <div class=\"list Tagahumika\">");
document.write("                    <a class=\"decorationlabel\" href=\"https://riztranslation.github.io/tagahumika\">");
document.write("                        <p class=\"label\"> Tagahumika</p>");
document.write("                    </a>");
document.write("                </div></a>");
document.write("                <div class=\"list osananajimi\">");
document.write("                    <a class=\"decorationlabel\" href=\"https://riztranslation.github.io/Osananajimi\">");
document.write("                        <p class=\"label\"> Osananajimi ni Modoritai Bokura</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list myhero\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Boku no Hero</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list ashita\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Ashita Shinu Shoujo no Saigo no Hokagou</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list mangaka\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Ore no Kanojo ga Mangaka ni naru</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list hitomebore\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Hitomebore</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list line\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> LINE Yang Tak Pernah Terbalas</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list nozokimi\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Nozokimi</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list zombie\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Zombie Darake ni Natta</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list sachan\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Drugstore Tenin Sa-chan no Nichijo</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list anotoki\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Anotoki Kara, Zutto</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("                <div class=\"list deliquent\">");
document.write("                    <a class=\"decorationlabel\" href=\"\">");
document.write("                        <p class=\"label\"> Moto Yan Kanojo to Majime-kun</p>");
document.write("                    </a>");
document.write("                </div>");
document.write("            </div>");
document.write("        </div>");
document.write("    </div>");
